# -*- coding: utf-8 -*-
"""session4 ML logistic regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJFiiWlk1sg7HPvjYXtcayUSwOMzRDDQ
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score  , recall_score , precision_score , confusion_matrix , classification_report ,f1_score

iris = load_iris()

iris

X = iris["data"]
y = iris["target"]

X

y

X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)

LR = LogisticRegression(multi_class= 'ovr')

LR.fit(X_train , y_train)

y_pred = LR.predict(X_test)

#Evaluation
accuracy = accuracy_score(y_test , y_pred)
recall = recall_score(y_test , y_pred , average = 'macro')
precision = precision_score(y_test , y_pred , average = 'macro')
f1 = f1_score(y_test , y_pred , average = 'macro')


print("Accuracy:", accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("F1 Score:", f1)

